"""FastHTML component for rendering the viewport-fit measurement script"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/components.ipynb.

# %% auto #0
__all__ = ['render_viewport_fit_script']

# %% ../nbs/components.ipynb #15929f2b
from typing import Any

from fasthtml.common import Script

from .models import ViewportFitConfig
from .js import generate_viewport_fit_js

# %% ../nbs/components.ipynb #412d9ac8
def render_viewport_fit_script(
    config: ViewportFitConfig,  # Instance configuration
) -> Any:  # Script element with complete viewport-fit JS
    """Render a Script element with the complete viewport-fit measurement JS."""
    return Script(generate_viewport_fit_js(config))
