"""JavaScript generation functions for viewport height measurement"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/js.ipynb.

# %% auto #0
__all__ = ['generate_debug_helpers_js', 'generate_space_below_js', 'generate_calculate_height_js', 'generate_resize_handler_js',
           'generate_htmx_settle_js', 'generate_sibling_observer_js', 'generate_init_js', 'generate_viewport_fit_js']

# %% ../nbs/js.ipynb #f7fb3572
from .models import ViewportFitConfig

# %% ../nbs/js.ipynb #e6020ff6
def generate_debug_helpers_js(
    config: ViewportFitConfig,  # Instance configuration
) -> str:  # JS debug helper closures
    """Generate debug logging helpers conditional on a window flag."""
    enable_line = f"window.{config.debug_flag} = true;" if config.debug else ""
    return f"""
    {enable_line}
    const _debug = () => window.{config.debug_flag} === true;
    const _log = (...args) => {{ if (_debug()) console.log('[{config.log_prefix}]', ...args); }};
"""

# %% ../nbs/js.ipynb #dc577d7f
def generate_space_below_js(
    config: ViewportFitConfig,  # Instance configuration
) -> str:  # JS function for DOM-walking space measurement
    """Generate JS that walks the DOM tree to measure space below a target element."""
    return f"""
    function _calculateSpaceBelow(target) {{
        let spaceBelow = 0;
        let currentElement = target;
        let currentRect = currentElement.getBoundingClientRect();
        let parent = target.parentElement;
        let level = 0;

        while (parent && parent !== document.documentElement) {{
            const parentStyles = getComputedStyle(parent);
            const paddingBottom = parseFloat(parentStyles.paddingBottom) || 0;
            const borderBottom = parseFloat(parentStyles.borderBottomWidth) || 0;
            const marginBottom = parseFloat(parentStyles.marginBottom) || 0;

            _log(`spaceBelow L${{level}}: parent=${{parent.tagName}}#${{parent.id || '(no id)'}}, padding=${{paddingBottom}}, border=${{borderBottom}}, margin=${{marginBottom}}`);

            let foundCurrent = false;
            for (const sibling of parent.children) {{
                if (sibling === currentElement) {{ foundCurrent = true; continue; }}
                if (!foundCurrent) continue;
                if (sibling.nodeType !== Node.ELEMENT_NODE) continue;
                const tag = sibling.tagName;
                if (tag === 'SCRIPT' || tag === 'STYLE') continue;
                if (tag === 'INPUT' && sibling.type === 'hidden') continue;
                const s = getComputedStyle(sibling);
                if (s.display === 'none') continue;

                const siblingRect = sibling.getBoundingClientRect();

                // Skip siblings beside (not below) in flex/grid rows
                if (siblingRect.top < currentRect.bottom) {{
                    _log(`  skip (beside): ${{tag}}#${{sibling.id || '(no id)'}}, top=${{siblingRect.top}} < bottom=${{currentRect.bottom}}`);
                    continue;
                }}

                const visualSpace = siblingRect.bottom - currentRect.bottom;
                spaceBelow += visualSpace;
                _log(`  below: ${{tag}}#${{sibling.id || '(no id)'}}, visualSpace=${{visualSpace}}`);

                currentRect = {{ bottom: siblingRect.bottom, top: currentRect.top }};
            }}

            spaceBelow += paddingBottom + borderBottom + marginBottom;

            currentElement = parent;
            currentRect = parent.getBoundingClientRect();
            parent = parent.parentElement;
            level++;
        }}
        return spaceBelow;
    }}
"""

# %% ../nbs/js.ipynb #aa945725
def generate_calculate_height_js(
    config: ViewportFitConfig,  # Instance configuration
) -> str:  # JS function for collapse-measure-apply height calculation
    """Generate JS that measures and applies viewport-fitted height to the target element."""
    # Inner element handling (optional)
    if config.inner_id:
        inner_lookup = f"const inner = document.getElementById('{config.inner_id}');"
        inner_collapse = "if (inner) inner.style.height = '0px';"
        inner_apply = "if (inner) inner.style.height = viewportHeight + 'px';"
    else:
        inner_lookup = ""
        inner_collapse = ""
        inner_apply = ""

    return f"""
    function _calculateAndSetHeight() {{
        const target = document.getElementById('{config.target_id}');
        {inner_lookup}
        if (!target) {{
            _log('ERROR: target element not found:', '{config.target_id}');
            return {config.min_height};
        }}

        _log('=== _calculateAndSetHeight ===');

        // Save current height
        const savedHeight = target.style.height;
        const savedMinHeight = target.style.minHeight;
        const savedMaxHeight = target.style.maxHeight;

        // Temporarily collapse to measure natural top position
        target.style.height = '0px';
        target.style.minHeight = '0px';
        target.style.maxHeight = '0px';
        {inner_collapse}

        // Force reflow
        target.offsetHeight;

        // Measure positions with collapsed target
        const targetRect = target.getBoundingClientRect();
        const spaceAbove = targetRect.top;
        const spaceBelow = _calculateSpaceBelow(target);

        // Collapsed target may still have non-zero height from padding/border.
        // For content-box, the applied height is ON TOP of padding/border,
        // so we must subtract the collapsed box height to avoid overflow.
        // For border-box, the applied height INCLUDES padding/border.
        const collapsedHeight = targetRect.bottom - targetRect.top;
        const targetBoxSizing = getComputedStyle(target).boxSizing;
        const boxAdjust = targetBoxSizing === 'border-box' ? 0 : collapsedHeight;

        const windowHeight = window.innerHeight;
        const rawHeight = windowHeight - spaceAbove - spaceBelow - boxAdjust;
        const viewportHeight = Math.floor(Math.max({config.min_height}, rawHeight));

        _log('windowHeight:', windowHeight);
        _log('spaceAbove:', spaceAbove);
        _log('spaceBelow:', spaceBelow);
        _log('collapsedHeight:', collapsedHeight, '(boxSizing:', targetBoxSizing + ', adjust:', boxAdjust + ')');
        _log('rawHeight:', rawHeight);
        _log('viewportHeight:', viewportHeight, rawHeight < {config.min_height} ? '(clamped to min)' : '');

        // Apply calculated height
        target.style.height = viewportHeight + 'px';
        target.style.maxHeight = viewportHeight + 'px';
        target.style.minHeight = viewportHeight + 'px';
        {inner_apply}

        return viewportHeight;
    }}
"""

# %% ../nbs/js.ipynb #f5da14e9
def generate_resize_handler_js(
    config: ViewportFitConfig,  # Instance configuration
) -> str:  # JS for debounced resize listener with cleanup
    """Generate debounced window resize handler with HTMX-safe cleanup."""
    callback_line = f"\n        {config.resize_callback}" if config.resize_callback else ""

    return f"""
    function _debounce(fn, delay) {{
        let tid;
        return function(...args) {{ clearTimeout(tid); tid = setTimeout(() => fn.apply(this, args), delay); }};
    }}

    const _debouncedResize = _debounce(function() {{
        _calculateAndSetHeight();{callback_line}
    }}, {config.debounce_ms});

    if (window.{config.handler_key}) {{
        window.removeEventListener('resize', window.{config.handler_key});
    }}
    window.{config.handler_key} = _debouncedResize;
    window.addEventListener('resize', _debouncedResize);
"""

# %% ../nbs/js.ipynb #0b46ebd5
def generate_htmx_settle_js(
    config: ViewportFitConfig,  # Instance configuration
) -> str:  # JS for HTMX afterSettle recalculation (empty if disabled)
    """Generate HTMX afterSettle handler for recalculation on SPA navigation."""
    if not config.enable_htmx_settle:
        return ""

    # Re-setup sibling observer after HTMX swaps replace DOM elements
    observer_setup = "if (typeof _setupSiblingObserver === 'function') _setupSiblingObserver();" if config.observe_siblings else ""

    return f"""
    function _onSettle() {{
        requestAnimationFrame(function() {{
            {observer_setup}
            _calculateAndSetHeight();
        }});
    }}

    if (window.{config.settle_handler_key}) {{
        document.body.removeEventListener('htmx:afterSettle', window.{config.settle_handler_key});
    }}
    window.{config.settle_handler_key} = _onSettle;
    document.body.addEventListener('htmx:afterSettle', _onSettle);
"""

# %% ../nbs/js.ipynb #atxkaq5vfst
def generate_sibling_observer_js(
    config: ViewportFitConfig,  # Instance configuration
) -> str:  # JS for ResizeObserver on ancestor-level siblings (empty if disabled)
    """Generate ResizeObserver that walks the DOM tree and watches visible siblings at all ancestor levels."""
    if not config.observe_siblings:
        return ""

    return f"""
    function _setupSiblingObserver() {{
        const target = document.getElementById('{config.target_id}');
        if (!target || !target.parentElement) return;

        // Disconnect previous observer (handles re-setup after HTMX swaps)
        if (window.{config.observer_key}) {{
            window.{config.observer_key}.disconnect();
        }}

        const _debouncedRecalc = _debounce(function() {{
            _log('layout change detected, recalculating');
            _calculateAndSetHeight();
        }}, {config.debounce_ms});

        const observer = new ResizeObserver(_debouncedRecalc);

        // Walk up the DOM tree mirroring _calculateSpaceBelow —
        // observe visible siblings at every ancestor level so that
        // changes anywhere in the layout trigger recalculation.
        let currentElement = target;
        let parent = target.parentElement;
        let level = 0;

        while (parent && parent !== document.documentElement) {{
            for (const sibling of parent.children) {{
                if (sibling === currentElement) continue;
                const tag = sibling.tagName;
                if (tag === 'SCRIPT' || tag === 'STYLE') continue;
                if (tag === 'INPUT' && sibling.type === 'hidden') continue;
                if (getComputedStyle(sibling).display === 'none') continue;
                observer.observe(sibling);
                _log('observing L' + level + ':', tag + '#' + (sibling.id || '(no id)'));
            }}
            currentElement = parent;
            parent = parent.parentElement;
            level++;
        }}

        window.{config.observer_key} = observer;
    }}
"""

# %% ../nbs/js.ipynb #342a0a6b
def generate_init_js(
    config: ViewportFitConfig,  # Instance configuration
) -> str:  # JS initialization block
    """Generate JS for initial measurement on script execution."""
    scroll_line = "window.scrollTo(0, 0);" if config.scroll_to_top else ""
    observer_setup = "_setupSiblingObserver();" if config.observe_siblings else ""

    return f"""
    requestAnimationFrame(function() {{
        setTimeout(function() {{
            {scroll_line}
            _calculateAndSetHeight();
            {observer_setup}
        }}, 50);
    }});
"""

# %% ../nbs/js.ipynb #6c73f9b7
def generate_viewport_fit_js(
    config: ViewportFitConfig,  # Instance configuration
) -> str:  # Complete JS code as a self-contained IIFE
    """Generate the complete viewport-fit JS as a self-contained IIFE."""
    parts = [
        generate_debug_helpers_js(config),
        generate_space_below_js(config),
        generate_calculate_height_js(config),
        generate_resize_handler_js(config),
        generate_htmx_settle_js(config),
        generate_sibling_observer_js(config),
        f"    window.{config.recalc_fn} = _calculateAndSetHeight;",
        generate_init_js(config),
    ]

    body = "\n".join(parts)
    return f"(function() {{{body}\n}})();"
