"""Configuration dataclass for viewport-fit measurement instances"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/models.ipynb.

# %% auto #0
__all__ = ['ViewportFitConfig']

# %% ../nbs/models.ipynb #aaa6714d
from dataclasses import dataclass

# %% ../nbs/models.ipynb #a2dfb590
@dataclass
class ViewportFitConfig:
    """Configuration for a viewport-fit measurement instance."""

    namespace: str  # Unique prefix for JS isolation (e.g., "source_select")
    target_id: str  # HTML ID of the element to fit to viewport height
    inner_id: str = ""  # Optional child element that also receives the calculated height
    min_height: int = 200  # Minimum height in pixels
    debounce_ms: int = 100  # Resize debounce delay in milliseconds
    scroll_to_top: bool = True  # Scroll to (0,0) before measuring (for HTMX SPAs)
    enable_htmx_settle: bool = True  # Remeasure on htmx:afterSettle events
    resize_callback: str = ""  # Optional JS expression called after resize
    debug: bool = False  # Enable debug console logging by default

    @property
    def ns(self) -> str:  # Capitalized namespace for JS function names
        """Capitalized namespace for JS function names."""
        return "".join(p.capitalize() for p in self.namespace.split("_"))

    @property
    def handler_key(self) -> str:  # Window-level key for resize handler cleanup
        """Window-level key for resize handler cleanup."""
        return f"_vfResizeHandler_{self.namespace.replace('-', '_')}"

    @property
    def settle_handler_key(self) -> str:  # Window-level key for HTMX settle handler
        """Window-level key for HTMX settle handler cleanup."""
        return f"_vfSettleHandler_{self.namespace.replace('-', '_')}"

    @property
    def debug_flag(self) -> str:  # JS window debug flag name
        """Window-level debug flag name."""
        return f"viewportFitDebug_{self.namespace.replace('-', '_')}"

    @property
    def log_prefix(self) -> str:  # Console log prefix string
        """Console log prefix string."""
        return f"vf:{self.namespace}"

    @property
    def recalc_fn(self) -> str:  # Global function name for manual recalculation
        """Global function name for manual recalculation."""
        return f"recalculate{self.ns}Height"
